### ISSUE TITLE
Add a "Name" tag to ec2 instances

### ISSUE THREAD

**Issue by lorengordon** [plus3it/terrafirm#9]
Use the `tags` option on the terraform ec2 resource to create a name tag for each instance so it is easier to identify the terrafirm instances.

**Comment by lorengordon** [comment]
Perhaps a nametag of `terraform-<build_id>`? Help make it easier to find the right logs for that instance if needed.

**Comment by YakDriver** [comment]
Wow. Great minds. Just committed that except I used an underscore.

**Comment by YakDriver** [comment]
New commit with a dash in name tag.
